---
title: "WheatResistance"
author: "Nicolas O. Rode"
date: "24 June 2016"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: true
---

# Data 2012
## Set working directory and load dataset
```{r}
setwd("/homedir/rode/Rstudio/Yan/2012-2015/18082016")
data <- read.table("~/Rstudio/Yan/2012/bilan_WSSMV.csv" , header=T , sep=";" , na.strings="NA")

## Replace the name of the dic2 genotypes
data$Num <- as.character(data$Num)
data$Num[data$Genealogie=="dic2"&!is.na(data$Genealogie)] <- as.character(data$N_preparation_semis_Melgueil_2010_2011[data$Genealogie=="dic2"&!is.na(data$Genealogie)])

# Je garde seulement les colonnes utilise :
data=data[ , c(1,5,6,19,21,26,27)]
head(data)
```

## Data preparation
```{r}
#Add columns for the neighbour genotypes --> 9 columns
Neighbour <- data.frame(matrix(c("neigh1","neigh2","neigh3","neigh8","focal genotype","neigh4","neigh7","neigh6","neigh5"),byrow=F,ncol=3))
colnames(Neighbour) <- c("Y1","Y2","Y3")
rownames(Neighbour) <- c("X1","X2","X3")
Neighbour
voisin=as.data.frame(matrix(0 , ncol=8 ,  nrow=750))
for(i in 1:nrow(data)){
    #print(i)
    ind=as.character(data$Num[data$X==data$X[i]-1 & data$Y==data$Y[i]-1]) ; if(length(ind)==0) { voisin[i,1]= "side1" } else { voisin[i,1]=ind }
    ind=as.character(data$Num[data$X==data$X[i]+0 & data$Y==data$Y[i]-1]) ; if(length(ind)==0) { voisin[i,2]= "side2" } else { voisin[i,2]=ind }
    ind=as.character(data$Num[data$X==data$X[i]+1 & data$Y==data$Y[i]-1]) ; if(length(ind)==0) { voisin[i,3]= "side3" } else { voisin[i,3]=ind }
    ind=as.character(data$Num[data$X==data$X[i]+1 & data$Y==data$Y[i]+0]) ; if(length(ind)==0) { voisin[i,4]= "side4" } else { voisin[i,4]=ind }
    ind=as.character(data$Num[data$X==data$X[i]+1 & data$Y==data$Y[i]+1]) ; if(length(ind)==0) { voisin[i,5]= "side5" } else { voisin[i,5]=ind }
    ind=as.character(data$Num[data$X==data$X[i]+0 & data$Y==data$Y[i]+1]) ; if(length(ind)==0) { voisin[i,6]= "side6" } else { voisin[i,6]=ind }
    ind=as.character(data$Num[data$X==data$X[i]-1 & data$Y==data$Y[i]+1]) ; if(length(ind)==0) { voisin[i,7]= "side7" } else { voisin[i,7]=ind }
    ind=as.character(data$Num[data$X==data$X[i]-1 & data$Y==data$Y[i]+0]) ; if(length(ind)==0) { voisin[i,8]= "side8" } else { voisin[i,8]=ind }
}
head(voisin)
data=cbind(data,voisin)
colnames(data)=c("plante","pop","genotype","NV","Elisa","X","Y","neigh1","neigh2","neigh3","neigh4","neigh5","neigh6","neigh7","neigh8")

data$neigh1<-factor(data$neigh1)
data$neigh2<-factor(data$neigh2)
data$neigh3<-factor(data$neigh3)
data$neigh4<-factor(data$neigh4)
data$neigh5<-factor(data$neigh5)
data$neigh6<-factor(data$neigh6)
data$neigh7<-factor(data$neigh7)
data$neigh8<-factor(data$neigh8)


head(data)
tail(data)
data$X_Y <- as.factor(paste(data$X,data$Y,sep="_"))

## 750 rows
nrow(data)

## Get rid of one genotype that is not replicated in 2012/2015
data$NV[data$genotype=="dic74031"&!is.na(data$genotype)] <- NA
data$Elisa[data$genotype=="dic74031"&!is.na(data$genotype)] <- NA


## Change name for Dic2
data$genotype[data$genotype=="dic2"&!is.na(data$pop)] <- rep("Dic2",length(data$genotype[data$genotype=="dic2"&!is.na(data$pop)]))
data$genotype[data$genotype=="lloyd"&!is.na(data$pop)] <- rep("Lloyd",length(data$genotype[data$genotype=="lloyd"&!is.na(data$pop)]))

popnew <- as.character(data$genotype)
popnew[data$pop=="Dic 2 x Lloyd"&!is.na(data$pop)] <- rep("Dic2 x Lloyd",length(popnew[data$pop=="Dic 2 x Lloyd"&!is.na(data$pop)]))
popnew[data$pop=="Dic 2 x Silur"&!is.na(data$pop)] <- rep("Dic2 x Silur",length(popnew[data$pop=="Dic 2 x Silur"&!is.na(data$pop)]))
popnew[data$pop=="Dic 2 x Soldur"&!is.na(data$pop)] <- rep("Dic2 x Soldur",length(popnew[data$pop=="Dic 2 x Soldur"&!is.na(data$pop)]))

table(popnew)
data$pop <- as.factor(popnew)

## Get rid of genotype with no replicate in 2012 or 2015
data$Elisa[data$pop=="dicD"&!is.na(data$pop)] <- rep(NA,length(data$pop[data$pop=="dicD"&!is.na(data$pop)]))
data$NV[data$pop=="dicD"&!is.na(data$pop)] <- rep(NA,length(data$pop[data$pop=="dicD"&!is.na(data$pop)]))
data$genotype[data$genotype=="dicD"&!is.na(data$genotype)] <- NA
data$pop[data$pop=="dicD"&!is.na(data$pop)] <- NA

## 54 rows with missing data
nrow(data[is.na(data$NV)|is.na(data$Elisa)|is.na(data$genotype),])

## Positive correlation between the two descriptors of the disease
cor.test(data$NV,data$Elisa)

## NA for missing/unknown genotypes in genotype and visual scores
data$NV <- ifelse(is.na(data$genotype),NA,data$NV)
data$Elisa<- ifelse(is.na(data$genotype),NA,data$Elisa)

## 30 missing genotypes
sum(is.na(data$genotype))
## 35 missing visual scores
sum(is.na(data$NV))
## 52 missing visual scores
sum(is.na(data$Elisa))

data <- data[order(data$Y,data$X),]

data2012<-data

write.csv(data2012,file="Data2012.csv",row.names=F,quote=F)
```

# Data 2015
## Load the data
```{r}
getwd()
data <- read.table("~/Rstudio/Yan/2015/Info_Pray_2015_lignes_dedoublees.csv" , header=T , sep=";" , na.strings="NA")

head(data)

# Ajout de colonne de position : A-10 --> X=1 , Y=10
data$cadrillage=as.character(data$cadrillage)
#Fabrication de 2 petites fonctions qui récupèrent les coordon?es x et y de la colonne de cadrillage
fun_x=function(x){strsplit(x,"-")[[1]][1]}
fun_y=function(x){strsplit(x,"-")[[1]][2] }
# Récupèration des informations concernant le cadrillage. (Je transforme le format A,B,C... en 1,2,3... + je retourne le vecteur pour que le 1 soit en haut (par d?fault la fonction levelplot me met le A en bas...)) :

#! order revrsed compared to 2012
data$Y=as.character(lapply(data$cadrillage , fun_x))
data$Y=match(data$Y, sort(unique(data$Y)))
data$X=as.numeric(lapply(data$cadrillage , fun_y))

# Je garde seulement les colonnes utilise :
data=data[,c(1,6,4,17,28,30,34,35)]
head(data)
```

## Data preparation
```{r}
#Ajout des colonnes des voisins ? --> 9 colonnes ? ajouter !
voisin=as.data.frame(matrix(0 , ncol=8 ,  nrow=750))
for(i in 1:nrow(data)){
    #print(i)
    ind=as.character(data$genealogie[data$X==data$X[i]-1 & data$Y==data$Y[i]-1]) ; if(length(ind)==0) { voisin[i,1]= "side1" } else { voisin[i,1]=ind }
    ind=as.character(data$genealogie[data$X==data$X[i]+0 & data$Y==data$Y[i]-1]) ; if(length(ind)==0) { voisin[i,2]= "side2" } else { voisin[i,2]=ind }
    ind=as.character(data$genealogie[data$X==data$X[i]+1 & data$Y==data$Y[i]-1]) ; if(length(ind)==0) { voisin[i,3]= "side3" } else { voisin[i,3]=ind }
    ind=as.character(data$genealogie[data$X==data$X[i]+1 & data$Y==data$Y[i]+0]) ; if(length(ind)==0) { voisin[i,4]= "side4" } else { voisin[i,4]=ind }
    ind=as.character(data$genealogie[data$X==data$X[i]+1 & data$Y==data$Y[i]+1]) ; if(length(ind)==0) { voisin[i,5]= "side5" } else { voisin[i,5]=ind }
    ind=as.character(data$genealogie[data$X==data$X[i]+0 & data$Y==data$Y[i]+1]) ; if(length(ind)==0) { voisin[i,6]= "side6" } else { voisin[i,6]=ind }
    ind=as.character(data$genealogie[data$X==data$X[i]-1 & data$Y==data$Y[i]+1]) ; if(length(ind)==0) { voisin[i,7]= "side7" } else { voisin[i,7]=ind }
    ind=as.character(data$genealogie[data$X==data$X[i]-1 & data$Y==data$Y[i]+0]) ; if(length(ind)==0) { voisin[i,8]= "side8" } else { voisin[i,8]=ind }
}

head(voisin)
data=cbind(data,voisin)
colnames(data)=c("plante","pop","genotype","NV","Elisa","QPCR","X","Y","neigh1","neigh2","neigh3","neigh4","neigh5","neigh6","neigh7","neigh8")

data$neigh1<-factor(data$neigh1)
data$neigh2<-factor(data$neigh2)
data$neigh3<-factor(data$neigh3)
data$neigh4<-factor(data$neigh4)
data$neigh5<-factor(data$neigh5)
data$neigh6<-factor(data$neigh6)
data$neigh7<-factor(data$neigh7)
data$neigh8<-factor(data$neigh8)


levels(data$pop) <- c("Dic2 x Lloyd", "Dic2" , "Dic2 x Soldur", "Dic2 x Silur", "Lloyd", "pescadou","Silur","Soldur")

head(data)
tail(data)
hist(data$NV)
hist(data$Elisa)

hist(log(data$QPCR))

plot(log(data$QPCR)~data$Elisa)
cor.test(log(data$QPCR),data$Elisa)

data$X_Y <- as.factor(paste(data$X,data$Y,sep="_"))
data$QPCR<-log(data$QPCR)

## 779 rows
nrow(data)

## 194 rows with missing data
nrow(data[is.na(data$NV)|is.na(data$Elisa)|is.na(data$genotype),])

## Positive correlation between the two descriptors of the disease
cor.test(data$NV,data$Elisa)

## NA for missing/unknown genotypes in genotype and visual scores
data$NV <- ifelse(is.na(data$genotype),NA,data$NV)
data$Elisa<- ifelse(is.na(data$genotype),NA,data$Elisa)

## 179 missing genotypes
sum(is.na(data$genotype))
## 185 missing visual scores
sum(is.na(data$NV))
## 189 missing visual scores
sum(is.na(data$Elisa))
## 324 missing qPCR values
sum(is.na(data$QPCR))

data <- data[order(data$Y,data$X),]

data2015<-data
write.csv(data2015,file="Data2015.csv",row.names=F,quote=F)
```

# Data 2012-2015
```{r}

QPCR<-rep(NA,nrow(data2012))

data2012<-data.frame(data2012[,1:5],QPCR,data2012[,6:16])
data2012$Year<-rep("2012",nrow(data2012))

data2015<-data2015[,1:17]
data2015$Year<-rep("2015",nrow(data2015))

data.frame(names(data2012),names(data2015))

data<-data.frame(rbind(data2012,data2015))
nrow(data)
head(data)

levels(data$pop)

data$genotype[data$pop=="Dic2"&!is.na(data$pop)]

data$genotype<-factor(data$genotype)

tapply(data$Year,list(data$Year,data$genotype),length)

levels(data$pop)

## Same level for all crosses
data$cross <- data$pop
levels(data$cross)[2:4] <- c("cross","cross","cross")


head(data)

levels(data$pop)
paper <- c("pescadou","Dic2 x Lloyd","Dic2 x Silur")
#paper <- c("Dic2","Lloyd","Silur","pescadou","Dic2 x Lloyd","Dic2 x Silur")

## Exclude data not used in the paper
data$NV <- ifelse(data$pop%in%paper,data$NV,NA)
data$Elisa <- ifelse(data$pop%in%paper,data$Elisa,NA)
data$QPCR <- ifelse(data$pop%in%paper,data$QPCR,NA)
data$pop <- as.factor(ifelse(data$pop%in%paper,as.character(data$pop),NA))


head(data)

write.csv(data,file="Data2012_2015.csv",row.names=F,quote=F)




```
